/* generated by gulpfile.js */
/*eslint camelcase: 0 */
import AudioCrawl from './updaters/AudioCrawl';
import AwesomeWebaudio from './updaters/AwesomeWebaudio';
export {
  AudioCrawl,
  AwesomeWebaudio
};
